version: '3.8'

services:
  postgres:
    container_name: postgres_container
    image: postgres:12
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    restart: unless-stopped

  pg-admin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:6
    environment:
      - PGADMIN_DEFAULT_EMAIL=elvaretharefa@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - "5050:5050"
    restart: unless-stopped
